/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-02-01 12:46:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MyProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("    <head>\n");
      out.write("        <title>MonsterMash - Game</title>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("        <meta name=\"description\" content=\"Monster Mash online Game\" />\n");
      out.write("        <meta name=\"keywords\" content=\"Game, Monster, Mash, on-line, gaming, fights\" />\n");
      out.write("        <meta name=\"author\" content=\"Group_07\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");

            String logout_url="logout.jsp";
            String profile_url="MyProfile.jsp";
            String monster_url="monster_farm.jsp";
        
      out.write("\n");
      out.write("        <div id=\"page-banner\">\n");
      out.write("        </div>\n");
      out.write("        <!-- Top menu bar.\n");
      out.write("        -->\n");
      out.write("        <div id=\"container-menu\">\n");
      out.write("            <ul>\n");
      out.write("                <!-- if session is active can go somewhere else? -->\n");
      out.write("                <li><a href=\"");
      out.print(profile_url);
      out.write("\">MyProfile</a></li>\n");
      out.write("                <li><a href=\"notification.html\">Notofication</a></li>\n");
      out.write("                <li><a href=\"");
      out.print(monster_url);
      out.write("\">Monsters</a></li>\n");
      out.write("                <li><a href=\"highscores.html\">Highscores</a></li>\n");
      out.write("                <li class=\"logout\"><a href=\"");
      out.print(logout_url);
      out.write("\">Log out</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        <!-- Spacing between top menu bar and main container. \n");
      out.write("        -->\n");
      out.write("        <div style=\"clear:both\"><p>&nbsp;</p></div>\n");
      out.write("        <!-- Main  container. \n");
      out.write("        -->\n");
      out.write("        <div id=\"container\">\n");
      out.write("            <p class=\"money\">MONEY: ");
      out.print( session.getAttribute("money") );
      out.write("</h3></p>\n");
      out.write("            <hr />\n");
      out.write("            <!--Freinds pan\n");
      out.write("            -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <p><table style=\"float:right; border: 1px solid #000;height:300px;width:215px;\">\n");
      out.write("                    <tr>\n");
      out.write("                        <td colspan=\"2\" style=\"text-align:top; height:40px; border-bottom: 1px solid #000;\">FRIENDS: <span style=\"float:right;width:50px;\">$</span></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr><td style=\"width:135px;\" colspan=\"2\">Player 1 <span style=\"float:right; width:50px;\">$ 900</span></td></tr>\n");
      out.write("                    <tr><td style=\"width:135px;\" colspan=\"2\">Player 2 <span style=\"float:right; width:50px;\">$ 800</span></td></tr>\n");
      out.write("                    <tr><td style=\"width:135px;\" colspan=\"2\">Player 3 <span style=\"float:right; width:50px;\">$ 2503</span></td></tr>\n");
      out.write("                    <tr><td style=\"width:135px;\" colspan=\"2\">Player 4 <span style=\"float:right; width:50px;\">$ 321</span></td></tr>\n");
      out.write("                    <tr><td style=\"width:135px;\" colspan=\"2\">Player 5 <span style=\"float:right; width:50px;\">$ 621</span></td></td></tr>\n");
      out.write("                    <tr><td style=\"width:135px;\" colspan=\"2\">Player 6 <span style=\"float:right; width:50px;\">$ 123</span></td></tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td  style=\"height: 40px; border-top: 1px solid #000;\" colspan=\"2\">\n");
      out.write("                            <input class=\"textfield\" type=\"text\" name=\"username\" maxlength=\"20\"/>\n");
      out.write("                            <input type=\"submit\" value=\"Add\" />\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                </table>\n");
      out.write("                <!--Notofication pan \n");
      out.write("                -->\n");
      out.write("                <div id=\"my_profile-left\"> \n");
      out.write("                       <h1>Profile</h1> \n");
      out.write("                       <p>Username: ");
      out.print( session.getAttribute("name") );
      out.write("</p>\n");
      out.write("                       <p>ID: ");
      out.print( session.getAttribute("ID"));
      out.write("</p>\n");
      out.write("                       <form action=\"Unregister\" method=\"post\">\n");
      out.write("                       <button class=\"button\">Unregister</button>\n");
      out.write("                       </form>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </p>\n");
      out.write("        </div>\n");
      out.write("        <div style=\"clear:both\"></div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
