/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-01-30 13:51:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.monstermash;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/monstermash/includes/footer.jsp", Long.valueOf(1359395319736L));
    _jspx_dependants.put("/monstermash/includes/header.jsp", Long.valueOf(1359395321891L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
 String base_url= "http://tomcat.thehiddennation.com/monstermash"; 
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Monster Mash</title>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("    <meta name=\"description\" content=\"MonsterMash - Group project\" />\r\n");
      out.write("    <meta name=\"keywords\" content=\"MonsterMash, games, gamer, gamming\" />\r\n");
      out.write("    <meta name=\"author\" content=\"Group 7\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( base_url );
      out.write("/static/normalize.css\" type=\"text/css\" />\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Finger+Paint' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( base_url );
      out.write("/static/theme.css\" type=\"text/css\" />\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  <div id=\"page\">\r\n");
      out.write("    <div id=\"header\" class=\"container\">\r\n");
      out.write("        <h1>Monster Mash</h1>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"");
      out.print( base_url );
      out.write("/\">Home</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( base_url );
      out.write("/register\">Register</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"main\" class=\"container\">\r\n");
      out.write("<!-- end:includes/header.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"login\">Login</h2>\r\n");
      out.write("<form class=\"login\" action=\"/login\" method=\"POST\">\r\n");
      out.write("    <p><input name=\"email\" type=\"text\" placeholder=\"email\"/></p>\r\n");
      out.write("    <p><input name=\"email\" type=\"text\" placeholder=\"password\"/></p>\r\n");
      out.write("    <p><input name=\"login\" type=\"submit\" value=\"Login\"/></p>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("    </div><!-- end:div#main -->\r\n");
      out.write("    <div id=\"footer\" class=\"container\">\r\n");
      out.write("        This is a project by Group 7. <a href=\"");
      out.print( base_url );
      out.write('"');
      out.write('>');
      out.print( base_url );
      out.write("</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
